#if !canImport(ObjectiveC)
import XCTest

extension MNPTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MNPTests = [
        ("testCRC", testCRC),
        ("testLinkRequestPacket", testLinkRequestPacket),
        ("testPacketLayerReadRequest", testPacketLayerReadRequest),
        ("testPacketLayerReadTransfer", testPacketLayerReadTransfer),
        ("testPacketLayerWrite", testPacketLayerWrite),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MNPTests.__allTests__MNPTests),
    ]
}
#endif
