#if !canImport(ObjectiveC)
import XCTest

extension NSOFTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NSOFTests = [
        ("testNSOF1", testNSOF1),
        ("testNSOF2", testNSOF2),
        ("testNSOF3", testNSOF3),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NSOFTests.__allTests__NSOFTests),
    ]
}
#endif
